/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        gold: {
          DEFAULT: "#D4AF37",
          light: "#F4D03F",
          dark: "#B8941F",
          50: "rgba(212, 175, 55, 0.05)",
          100: "rgba(212, 175, 55, 0.1)",
          200: "rgba(212, 175, 55, 0.2)",
          500: "#D4AF37",
        },
        navy: {
          900: "#060912",
          800: "#0a0e1a",
          700: "#0d1221",
          600: "#111827",
          500: "#1a2236",
        },
        primary: {
          DEFAULT: "#D4AF37",
          dark: "#B8941F",
          light: "#F4D03F",
          foreground: "#060912",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "#D4AF37",
          foreground: "#060912",
        },
        success: { DEFAULT: "#10b981", foreground: "#fff" },
        danger: { DEFAULT: "#ef4444", foreground: "#fff" },
        warning: { DEFAULT: "#f59e0b", foreground: "#fff" },
        info: { DEFAULT: "#3b82f6", foreground: "#fff" },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        "2xl": "16px",
        "3xl": "24px",
      },
      fontFamily: {
        display: ['"Space Grotesk"', "sans-serif"],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        gold: "0 0 30px rgba(212, 175, 55, 0.2), 0 0 60px rgba(212, 175, 55, 0.08)",
        "gold-sm": "0 0 15px rgba(212, 175, 55, 0.15)",
        "gold-lg": "0 0 40px rgba(212, 175, 55, 0.25), 0 0 80px rgba(212, 175, 55, 0.1)",
        red: "0 0 30px rgba(220, 38, 38, 0.2), 0 0 60px rgba(220, 38, 38, 0.08)",
        green: "0 0 30px rgba(16, 185, 129, 0.2), 0 0 60px rgba(16, 185, 129, 0.08)",
        blue: "0 0 30px rgba(59, 130, 246, 0.2), 0 0 60px rgba(59, 130, 246, 0.08)",
        elevated: "0 8px 32px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(212, 175, 55, 0.04)",
        card: "0 4px 16px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.04)",
        button: "0 4px 20px rgba(212, 175, 55, 0.25), inset 0 1px 0 rgba(255, 255, 255, 0.2)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "float": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-12px)" } },
        "float-slow": { "0%, 100%": { transform: "translateY(0) rotate(0deg)" }, "50%": { transform: "translateY(-8px) rotate(2deg)" } },
        "pulse-gold": { "0%, 100%": { boxShadow: "0 0 0 0 rgba(212, 175, 55, 0)" }, "50%": { boxShadow: "0 0 30px 4px rgba(212, 175, 55, 0.25)" } },
        "slide-up": { from: { transform: "translateY(30px)", opacity: "0" }, to: { transform: "translateY(0)", opacity: "1" } },
        "slide-in-right": { from: { transform: "translateX(40px)", opacity: "0" }, to: { transform: "translateX(0)", opacity: "1" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "scale-in": { from: { transform: "scale(0.9)", opacity: "0" }, to: { transform: "scale(1)", opacity: "1" } },
        "spin-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "float": "float 5s ease-in-out infinite",
        "float-slow": "float-slow 7s ease-in-out infinite",
        "pulse-gold": "pulse-gold 2.5s ease-in-out infinite",
        "slide-up": "slide-up 0.6s cubic-bezier(0.23, 1, 0.32, 1)",
        "slide-in-right": "slide-in-right 0.6s cubic-bezier(0.23, 1, 0.32, 1)",
        "fade-in": "fade-in 0.4s ease-out",
        "scale-in": "scale-in 0.4s cubic-bezier(0.23, 1, 0.32, 1)",
        "spin-slow": "spin-slow 20s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
