/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#00a8e8",
          dark: "#0077b6",
          light: "rgba(0, 168, 232, 0.15)",
          foreground: "#FFFFFF",
        },
        secondary: {
          DEFAULT: "#1e293b",
          foreground: "#e2e8f0",
        },
        accent: {
          DEFAULT: "#fbbf24",
          foreground: "#0a0e1a",
        },
        danger: {
          DEFAULT: "#ef4444",
          foreground: "#FFFFFF",
        },
        success: {
          DEFAULT: "#10b981",
          foreground: "#FFFFFF",
        },
        warning: {
          DEFAULT: "#f59e0b",
          foreground: "#FFFFFF",
        },
        info: {
          DEFAULT: "#3b82f6",
          foreground: "#FFFFFF",
        },
        surface: {
          DEFAULT: "rgba(30, 41, 59, 0.6)",
          light: "rgba(255, 255, 255, 0.03)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        navy: {
          900: '#0a0e1a',
          800: '#0d1b2a',
          700: '#0d2b3e',
          600: '#0a1628',
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.2)",
        card: "0 4px 16px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255,255,255,0.05)",
        elevated: "0 8px 32px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255,255,255,0.06)",
        button: "0 4px 14px rgba(0, 168, 232, 0.3), inset 0 1px 0 rgba(255,255,255,0.1)",
        glow: "0 0 20px rgba(0, 168, 232, 0.25), 0 0 40px rgba(0, 168, 232, 0.1)",
        'glow-gold': "0 0 20px rgba(251, 191, 36, 0.25), 0 0 40px rgba(251, 191, 36, 0.1)",
        'glow-danger': "0 0 20px rgba(220, 38, 38, 0.25)",
        'glow-success': "0 0 20px rgba(5, 150, 105, 0.25)",
        inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.2)",
        glass: "inset 0 1px 1px rgba(255,255,255,0.08), 0 4px 16px rgba(0,0,0,0.3)",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "slide-up": { from: { transform: "translateY(20px)", opacity: "0" }, to: { transform: "translateY(0)", opacity: "1" } },
        "slide-down": { from: { transform: "translateY(-20px)", opacity: "0" }, to: { transform: "translateY(0)", opacity: "1" } },
        "slide-in-right": { from: { transform: "translateX(20px)", opacity: "0" }, to: { transform: "translateX(0)", opacity: "1" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "scale-in": { from: { transform: "scale(0.95)", opacity: "0" }, to: { transform: "scale(1)", opacity: "1" } },
        "float": { "0%, 100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-8px)" } },
        "pulse-glow": { "0%, 100%": { boxShadow: "0 0 0 0 rgba(0, 168, 232, 0)" }, "50%": { boxShadow: "0 0 20px 4px rgba(0, 168, 232, 0.3)" } },
        "pulse-glow-danger": { "0%, 100%": { boxShadow: "0 0 0 0 rgba(220, 38, 38, 0)" }, "50%": { boxShadow: "0 0 20px 4px rgba(220, 38, 38, 0.3)" } },
        "shimmer": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "spin-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "bounce-subtle": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-4px)" } },
        "gradient-shift": { "0%": { backgroundPosition: "0% 50%" }, "50%": { backgroundPosition: "100% 50%" }, "100%": { backgroundPosition: "0% 50%" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-up": "slide-up 0.5s cubic-bezier(0.32, 0.72, 0, 1)",
        "slide-down": "slide-down 0.5s cubic-bezier(0.32, 0.72, 0, 1)",
        "slide-in-right": "slide-in-right 0.5s cubic-bezier(0.32, 0.72, 0, 1)",
        "fade-in": "fade-in 0.3s ease-out",
        "scale-in": "scale-in 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        "float": "float 4s ease-in-out infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "pulse-glow-danger": "pulse-glow-danger 2s ease-in-out infinite",
        "shimmer": "shimmer 3s ease-in-out infinite",
        "spin-slow": "spin-slow 12s linear infinite",
        "bounce-subtle": "bounce-subtle 2s ease-in-out infinite",
        "gradient-shift": "gradient-shift 8s ease infinite",
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
